CREATE DATABASE Test1

CREATE TABLE Statuses(
Status_Id INT IDENTITY(1,1) NOT NULL,
Status_Type VARCHAR(10) NOT NULL,
Status_Name VARCHAR(50) NOT NULL
CONSTRAINT PK_Statuses PRIMARY KEY CLUSTERED(
Status_Id)
)

CREATE TABLE Categories(
Category_Id INT IDENTITY(1,1) NOT NULL,
Category_Name VARCHAR(50) NOT NULL
CONSTRAINT PK_Categories PRIMARY KEY CLUSTERED(
Category_Id)
)

CREATE TABLE Authors(
Author_Id INT IDENTITY(1,1) NOT NULL,
Author_Document VARCHAR(15) NOT NULL,
Author_Name VARCHAR(50) NOT NULL
CONSTRAINT PK_Authors PRIMARY KEY CLUSTERED(
Author_Id)
)

CREATE TABLE Books(
Book_Id INT IDENTITY(1,1) NOT NULL,
Book_Name VARCHAR(80) NOT NULL,
Number_Of_Pages INT NOT NULL,
Book_Category_Id INT NOT NULL FOREIGN KEY REFERENCES Categories(Category_Id),
Author_Id INT NOT NULL FOREIGN KEY REFERENCES Authors(Author_Id),
Book_Status_Id INT NOT NULL FOREIGN KEY REFERENCES Statuses(Status_Id)
CONSTRAINT PK_Books PRIMARY KEY CLUSTERED(
Book_Id)
)

CREATE TABLE User_Types(
User_Type_Id INT IDENTITY(1,1) NOT NULL,
User_Type_Name VARCHAR(50) NOT NULL
CONSTRAINT PK_User_Types PRIMARY KEY CLUSTERED(
User_Type_Id)
)

CREATE TABLE Users(
User_Id INT IDENTITY(1,1) NOT NULL,
User_Document VARCHAR(15) NOT NULL,
User_Password VARCHAR(10) NULL,
User_Name VARCHAR(50) NOT NULL,
User_Last_Name VARCHAR(50) NOT NULL,
Phone_Number VARCHAR(10) NOT NULL,
Cell_Phone_Number VARCHAR(20) NOT NULL,
Address VARCHAR(50) NOT NULL,
Country_Of_Birth VARCHAR(2) NOT NULL,
Date_Of_Birth DATE NOT NULL,
User_Type_Id INT NOT NULL FOREIGN KEY REFERENCES User_Types(User_Type_Id),
User_Status_Id INT NOT NULL FOREIGN KEY REFERENCES Statuses(Status_Id)
CONSTRAINT PK_Users PRIMARY KEY CLUSTERED(
User_Id)
)

CREATE TABLE Bookings(
Booking_Id INT IDENTITY(1,1) NOT NULL,
Date_Of_Booking DATE NOT NULL,
Date_Of_Return DATE NOT NULL,
Book_Id INT NOT NULL FOREIGN KEY REFERENCES Books(Book_Id),
Booking_Status_Id INT NOT NULL FOREIGN KEY REFERENCES Statuses(Status_Id),
Booking_User_Id INT NOT NULL FOREIGN KEY REFERENCES Users(User_Id),
CONSTRAINT PK_Bookings PRIMARY KEY CLUSTERED(
Booking_Id)
)

ALTER TABLE Bookings ADD FOREIGN KEY (Booking_User_Id) REFERENCES Users(User_Id,)